/**
 * movimentationsList.java
 */
package vaadinapp.view;

import vaadinapp.Controller;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Marco Casella
 *
 */
public class MovimentationsListView extends CustomComponent implements  View , ClickListener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Table lists;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button newit;
	@AutoGenerated
	private Button edit;
	@AutoGenerated
	private Button back;
	private static final long serialVersionUID = -1062391231707169028L;
	public static final String NAME = "MovimentationsList";
	private VaadinSession session = VaadinSession.getCurrent();
	private Controller controller = session.getAttribute(Controller.class);
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MovimentationsListView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		lists.setContainerDataSource(controller.getMovimentationsContainer());
		newit.addClickListener(this);
	}

	/* (non-Javadoc)
	 * @see com.vaadin.navigator.View#enter(com.vaadin.navigator.ViewChangeListener.ViewChangeEvent)
	 */
	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		mainLayout.addComponent(verticalLayout_1,
				"top:20.0px;right:20.0px;bottom:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_1.addComponent(horizontalLayout_1);
		
		// lists
		lists = new Table();
		lists.setImmediate(false);
		lists.setWidth("100.0%");
		lists.setHeight("100.0%");
		verticalLayout_1.addComponent(lists);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("40px");
		horizontalLayout_1.setMargin(false);
		
		// back
		back = new Button();
		back.setCaption("Back");
		back.setImmediate(true);
		back.setWidth("50.0%");
		back.setHeight("-1px");
		horizontalLayout_1.addComponent(back);
		horizontalLayout_1.setComponentAlignment(back, new Alignment(20));
		
		// edit
		edit = new Button();
		edit.setCaption("Edit");
		edit.setImmediate(true);
		edit.setWidth("50.0%");
		edit.setHeight("-1px");
		horizontalLayout_1.addComponent(edit);
		
		// newit
		newit = new Button();
		newit.setCaption("New");
		newit.setImmediate(true);
		newit.setWidth("50.0%");
		newit.setHeight("-1px");
		horizontalLayout_1.addComponent(newit);
		
		return horizontalLayout_1;
	}

	/* (non-Javadoc)
	 * @see com.vaadin.ui.Button.ClickListener#buttonClick(com.vaadin.ui.Button.ClickEvent)
	 */
	@Override
	public void buttonClick(ClickEvent event) {
		final Button source = event.getButton();

		if (source==newit) 
			getUI().getNavigator().navigateTo(MovimentationsView.NAME);
			

		
	}

}
