CREATE PROCEDURE DOMOV (mov_spec_id int, mul int) 
	MODIFIES SQL DATA
	BEGIN ATOMIC
		INSERT INTO INVENTORY (SITE, ARTICLE) 
			SELECT MOVIMENTATIONS.SITE, MOVIMENTATION_SPECS.ID_ART 
			FROM MOVIMENTATION_SPECS JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID 
			WHERE MOVIMENTATION_SPECS.ID = mov_spec_id
				AND NOT EXISTS (
					SELECT 1
					FROM INVENTORY 
	 					JOIN ARTICLES ON INVENTORY.ARTICLE = ARTICLES.ID 
	 					JOIN MOVIMENTATION_SPECS ON INVENTORY.ARTICLE = MOVIMENTATION_SPECS.ID_ART
	 					JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
	 					JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
	 				WHERE MOVIMENTATION_SPECS.ID = mov_spec_id ); 
 		UPDATE INVENTORY SET INVENTORY.QUANTITY=INVENTORY.QUANTITY+(MOVIMENTATION_SPECS.QUANTITY * mul * MOVIMENTATION_TYPES.QUANTITY_EFFECT) 
     		FROM INVENTORY 
     			JOIN ARTICLES ON INVENTORY.ARTICLE = ARTICLES.ID 
     			JOIN MOVIMENTATION_SPECS ON INVENTORY.ARTICLE = MOVIMENTATION_SPECS.ID_ART
     			JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = mov_spec_id;
     END