# File contentente le query di inizializzazione database
CREATE TABLE USERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, USER VARCHAR(255) UNIQUE NOT NULL, PASS VARCHAR(255) NOT NULL, LEVEL INT NOT NULL); 
INSERT INTO USERS VALUES (NULL,'admin','70b3f062173dafebc53c2ef9bf20e17d9b0e63d2',99);
CREATE TABLE ARTICLES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255), PRICE INT);
INSERT INTO ARTICLES VALUES (NULL,'ARTICOLO1','TEST1',10);
INSERT INTO ARTICLES VALUES (NULL,'ARTICOLO2','TEST2',10);
INSERT INTO ARTICLES VALUES (NULL,'ARTICOLO3','TEST3',10);
INSERT INTO ARTICLES VALUES (NULL,'ARTICOLO4','TEST4',10);

                    
		         	
		         	
                    
