CREATE TABLE USERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, USER VARCHAR(255) UNIQUE NOT NULL, PASS VARCHAR(255) NOT NULL, LEVEL INT NOT NULL); 
INSERT INTO USERS VALUES (NULL,'admin','70b3f062173dafebc53c2ef9bf20e17d9b0e63d2',99);
                    
		         	
		         	
                    
