# File contentente le query di inizializzazione database
CREATE TABLE USERS (ID INTEGER PRIMARY KEY AUTOINCREMENT, USER VARCHAR(255) UNIQUE NOT NULL, PASS VARCHAR(255) NOT NULL, LEVEL INT NOT NULL); 
CREATE TABLE GROUPS (ID INTEGER PRIMARY KEY AUTOINCREMENT, FATHER_ID INTEGER REFERENCES GROUPS (ID) DEFAULT NULL, DESCRIPTION CHAR(256) );
CREATE TABLE ARTICLES (ID INTEGER PRIMARY KEY AUTOINCREMENT, GROUP_ID INTEGER REFERENCES GROUPS, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255), PRICE INT);
CREATE TABLE MOVIMENTATION (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPTION VARCHAR(255));
CREATE TABLE MOVIMENTATION_SPEC(ID INTEGER PRIMARY KEY AUTOINCREMENT, ID_HEAD INTEGER REFERENCES MOVIMENTATION (ID), ID_ART INTEGER REFERENCES MOVIMENTATION (ID), QUANTITY INTEGER, PRICE DECIMAL(10,2));
INSERT INTO USERS VALUES (NULL,'admin','70b3f062173dafebc53c2ef9bf20e17d9b0e63d2',99);
INSERT INTO GROUPS VALUES (NULL,NULL,'GENERALE');
INSERT INTO ARTICLES VALUES (NULL,last_insert_rowid(), 'ARTICOLO1','TEST1',10);
             