INSERT INTO SEASONS VALUES (NULL, 'N/A',0);

INSERT INTO COLORS VALUES (NULL, 'N/A',0);

INSERT INTO SIZES VALUES (NULL, 'N/A',0);

INSERT INTO MOVIMENTATION_TYPES VALUES (NULL, 'SELL' , -1 ,0 );

INSERT INTO MOVIMENTATION_TYPES VALUES (NULL, 'BUY' , +1 ,0 );

INSERT INTO SITES VALUES (NULL, 'CENTRAL','DEFAULT SITE',0);

INSERT INTO SITES VALUES (NULL, 'SECONDARY','SECONDARY SITE',0);

INSERT INTO USERS VALUES (NULL,'admin','70b3f062173dafebc53c2ef9bf20e17d9b0e63d2',99,0,0);

INSERT INTO USERS VALUES (NULL,'user','70b3f062173dafebc53c2ef9bf20e17d9b0e63d2',99,0,0);

INSERT INTO CATEGORIES VALUES (NULL,NULL,'MAIN',0);

INSERT INTO ARTICLES VALUES (NULL, 0, 'ART1','TEST1', 0, 0, 0, 10, 0, 0);





