CREATE TRIGGER MOVIMENTATION_SPECS_INS AFTER INSERT ON MOVIMENTATION_SPECS REFERENCING NEW ROW AS newrow FOR EACH ROW
	BEGIN ATOMIC
	DECLARE SITEID,	ARTID, Q, EFFECT INT;
	SET SITEID  = SELECT MOVIMENTATIONS.SITE FROM MOVIMENTATION_SPECS
				JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    SET ARTID = newrow.id;
    SET Q = newrow.QUANTITY;
    SET EFFECT = SELECT MOVIMENTATION_TYPES.QUANTITY_EFFECT FROM MOVIMENTATION_SPECS 
     			JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    CALL DOMOV (SITEID, ARTID, Q, EFFECT, 1);
    END
    
  
  CREATE TRIGGER MOVIMENTATION_SPECS_DEL AFTER DELETE ON MOVIMENTATION_SPECS REFERENCING OLD ROW AS newrow FOR EACH ROW
	BEGIN ATOMIC
	DECLARE SITEID, ARTID, Q, EFFECT INT;
	SET SITEID  = SELECT MOVIMENTATIONS.SITE FROM MOVIMENTATION_SPECS
				JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    SET ARTID = newrow.id;
    SET Q = newrow.QUANTITY;
    SET EFFECT = SELECT MOVIMENTATION_TYPES.QUANTITY_EFFECT FROM MOVIMENTATION_SPECS 
     			JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    CALL DOMOV (SITEID, ARTID, Q, EFFECT, -1);
    END  
    
  
  CREATE TRIGGER MOVIMENTATION_SPECS_UPD AFTER UPDATE ON MOVIMENTATION_SPECS REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	BEGIN ATOMIC
	DECLARE SITEID, ARTID, Q_OLD, Q_NEW, EFFECT INT;
	SET SITEID  = SELECT MOVIMENTATIONS.SITE FROM MOVIMENTATION_SPECS
				JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    SET ARTID = newrow.id;
    SET Q_OLD = oldrow.QUANTITY;
    SET Q_NEW = newrow.QUANTITY;
    SET EFFECT = SELECT MOVIMENTATION_TYPES.QUANTITY_EFFECT FROM MOVIMENTATION_SPECS 
     			JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
     		WHERE MOVIMENTATION_SPECS.ID = newrow.id;
    CALL DOMOV (SITEID, ARTID, Q_OLD, EFFECT, -1);
    CALL DOMOV (SITEID, ARTID, Q_NEW, EFFECT, 1);
  END
  

 COMMIT;

.;


