CREATE PROCEDURE DOMOV (site_id int, art_id int, q int, effect int, mul int) 
	MODIFIES SQL DATA
	BEGIN ATOMIC
		IF NOT EXISTS (SELECT 1 FROM INVENTORY WHERE SITE = site_id AND ARTICLE = art_id) THEN 
			INSERT INTO INVENTORY (SITE, ARTICLE) VALUES (site_id,art_id );
		END IF;
		UPDATE INVENTORY SET QUANTITY = QUANTITY + ( q * effect * mul) WHERE SITE = site_id AND ARTICLE = art_id;
		UPDATE ARTICLES SET QUANTITY = QUANTITY + ( q * effect * mul) WHERE ID = art_id;
	END;
	
.;
	
CREATE PROCEDURE DOMOVFROMROW (rowid int, mul int) 
	MODIFIES SQL DATA
	BEGIN ATOMIC
		DECLARE SITEID, ARTID, Q, EFFECT INT;
		SET SITEID  = SELECT MOVIMENTATIONS.SITE FROM MOVIMENTATION_SPECS
					JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
	     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
	     		WHERE MOVIMENTATION_SPECS.ID = rowid;
	    SET ARTID = SELECT ID_ART FROM MOVIMENTATION_SPECS WHERE ID = rowid;
	    SET Q = SELECT QUANTITY FROM MOVIMENTATION_SPECS WHERE ID = rowid;
	    SET EFFECT = SELECT MOVIMENTATION_TYPES.QUANTITY_EFFECT FROM MOVIMENTATION_SPECS 
	     			JOIN MOVIMENTATIONS ON MOVIMENTATION_SPECS.ID_HEAD = MOVIMENTATIONS.ID
	     			JOIN MOVIMENTATION_TYPES ON MOVIMENTATIONS.MOVIMENTATION_TYPE = MOVIMENTATION_TYPES.ID
	     		WHERE MOVIMENTATION_SPECS.ID = rowid;
	    IF NOT EXISTS (SELECT 1 FROM INVENTORY WHERE SITE = SITEID AND ARTICLE = ARTID) THEN 
			INSERT INTO INVENTORY (SITE, ARTICLE) VALUES ( SITEID , ARTID );
		END IF;
		UPDATE INVENTORY SET QUANTITY = QUANTITY + ( Q * EFFECT * mul) WHERE SITE = SITEID AND ARTICLE = ARTID;
		UPDATE ARTICLES SET QUANTITY = QUANTITY + ( Q * EFFECT * mul) WHERE ID = ARTID;
	END;


.;

CREATE PROCEDURE DOUPDATE (oldrowid int, newrowid int) 
	MODIFIES SQL DATA
	BEGIN ATOMIC
		CALL DOMOVFROMROW (oldrowid , -1);
		CALL DOMOVFROMROW (newrowid , 1);
	END;


.;

