CREATE TRIGGER SITES_VERSION BEFORE UPDATE ON SITES
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER USERS_VERSION BEFORE UPDATE ON USERS
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER COLORS_VERSION BEFORE UPDATE ON COLORS
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER SEASONS_VERSION BEFORE UPDATE ON SEASONS
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER SIZES_VERSION BEFORE UPDATE ON SIZES
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER CATEGORIES_VERSION BEFORE UPDATE ON CATEGORIES
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER ARTICLES_VERSION BEFORE UPDATE ON ARTICLES 
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER REGISTRY_VERSION BEFORE UPDATE ON REGISTRY
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER MOVIMENTATION_TYPES_VERSION BEFORE UPDATE ON MOVIMENTATION_TYPES
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER MOVIMENTATIONS_VERSION BEFORE UPDATE ON MOVIMENTATIONS
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER MOVIMENTATION_SPECS_VERSION BEFORE UPDATE ON MOVIMENTATION_SPECS
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;
	
CREATE TRIGGER INVENTORY_VERSION BEFORE UPDATE ON INVENTORY
	REFERENCING NEW ROW AS newrow OLD ROW AS oldrow FOR EACH ROW
	SET newrow.VERSIONID = oldrow.VERSIONID+1;


COMMIT;



