CREATE TABLE SITES (ID int NOT NULL AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, INFORMATION VARCHAR(255), VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE USERS (ID int NOT NULL AUTO_INCREMENT, USERNAME VARCHAR(255) UNIQUE NOT NULL, PASS VARCHAR(255) NOT NULL, LEVEL INT NOT NULL, SITE INTEGER REFERENCES SITES, VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID)); 

CREATE TABLE COLORS (ID int NOT NULL AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE SEASONS (ID int NOT NULL AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE SIZES(ID int NOT NULL AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL , VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE CATEGORIES (ID int NOT NULL AUTO_INCREMENT, FATHER_ID INTEGER REFERENCES CATEGORIES, CATEGORY VARCHAR(256), VERSIONID INT DEFAULT 0  NOT NULL, PRIMARY KEY (ID));

CREATE TABLE ARTICLES (ID int NOT NULL AUTO_INCREMENT, CATEGORY INTEGER REFERENCES CATEGORIES, NAME VARCHAR(255) NOT NULL, DESCRIPTION VARCHAR(255), COLOR INTEGER REFERENCES COLORS, SEASON INTEGER REFERENCES SEASONS, SIZE INTEGER REFERENCES SIZES, PRICE DECIMAL(10,2), QUANTITY INT DEFAULT 0, VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE REGISTRY (ID int NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), STREET VARCHAR(255), CITY VARCHAR(255), EMAIL VARCHAR(255), PHONE VARCHAR(255) , VERSIONID INT DEFAULT 0  NOT NULL, PRIMARY KEY (ID));

CREATE TABLE MOVIMENTATION_TYPES (ID int NOT NULL AUTO_INCREMENT, DESCRIPTION VARCHAR(255), QUANTITY_EFFECT INTEGER, VERSIONID INT DEFAULT 0  NOT NULL, PRIMARY KEY (ID));	

CREATE TABLE MOVIMENTATIONS (ID int NOT NULL AUTO_INCREMENT, OPDATE DATE, MOVIMENTATION VARCHAR(255), SITE INTEGER NOT NULL REFERENCES SITES ON DELETE CASCADE, MOVIMENTATION_TYPE INT NOT NULL REFERENCES MOVIMENTATION_TYPES, INTERNALDESTINATION INT DEFAULT NULL REFERENCES SITES ON DELETE CASCADE, DESTINATION INT, TOTAL DECIMAL(10,2), VERSIONID INT DEFAULT 0  NOT NULL, PRIMARY KEY (ID));

CREATE TABLE MOVIMENTATION_SPECS(ID int NOT NULL AUTO_INCREMENT, ID_HEAD INTEGER REFERENCES MOVIMENTATIONS ON DELETE CASCADE, SITE INTEGER NOT NULL REFERENCES SITES , MOVIMENTATION_TYPE INT NOT NULL REFERENCES MOVIMENTATION_TYPES, ID_ART INTEGER REFERENCES ARTICLES, QUANTITY INTEGER, PRICE DECIMAL(10,2), DISCOUNT DECIMAL(10,2), TOTAL DECIMAL(10,2), VERSIONID INT DEFAULT 0 NOT NULL, PRIMARY KEY (ID));

CREATE TABLE INVENTORY (SITE INT NOT NULL REFERENCES SITES ON DELETE CASCADE , ARTICLE INT NOT NULL REFERENCES ARTICLES ON DELETE CASCADE, QUANTITY INT DEFAULT 0, VERSIONID INT DEFAULT 0 NOT NULL, CONSTRAINT SITEART PRIMARY KEY ( SITE, ARTICLE ) );




